name: mint_pids

on:
  workflow_dispatch

env:
    HANDLE_USERNAME: ${{ secrets.HANDLE_USERNAME }}
    HANDLE_PASSWORD: ${{ secrets.HANDLE_PASSWORD }}

jobs:
  mint:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-python@v5
          with:
            python-version: '3.11'
            cache: 'pip'
        - run: pip install -r requirements.txt
        - name: mint
          run: python create_pids.py
        - name: Commit data
          uses: stefanzweifel/git-auto-commit-action@v5
          with:
            commit_message: new handles minted